remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Curriculum Vitae of Stefano Siani
description: Expert in digital forensics, cyber investigations and forensic analysis.
